#!/bin/bash

## convert a '.tmx' map file generated by Tiled

if [[ -z ${1} ]]; then
	echo "[Usage]: ${0} <file> <width> <height>"
fi


colliders="(2|5|10|7|8|9|10|11|12|15|16|17|19|20|22|23|24|27|28|29|30|31|32|33|34|39|47|48|57|58|59|69)"

awk -v map_width=${2} 'BEGIN { RS = ","; count = 0 }
{
	printf("%d,", $1 - 1);

	if (count == map_width) {
		printf("\n"); count = 0;
	} else {
		count++;
	}
}' <(head -$(($3 + 7)) ${1} | tail -${3}) | sed -E '$s/.$//;s/\b'"${colliders}"'\b/-&/g'
